### ISSUE TITLE
ILI9488 vs ILI9341

### ISSUE THREAD

**Issue by Sampozzo** [moononournation/arduino-nofrendo#4]
Hello again me on this great project :) 
I solved my previous SD problem (i posted my solution), but now i have another problem.

I switched my first test screen from a ILI9341 320x240 to an ILI9488 480x320.

The problem now is that the display_write_frame need to do some maths to crop and scale the original NES resolution to fit the bigger 480x320 and it really slow down the gameplay. 
Games that runs at full speed at original resolution, now are unplayable speed scaled.
I've tryed all the four options in the example with no acceptable speed.

Is this a known issue or i'm doing sometings wrong?
This is the code used to initialize the screen driver:

```
Arduino_DataBus *bus = new Arduino_ESP32SPI(32 /* DC */, -1 /* CS */, 25 /* SCK */, 33 /* MOSI */, -1 /* MISO */);
Arduino_ILI9488_18bit *gfx =new Arduino_ILI9488_18bit(bus, -1 /* RST */, 1 /* rotation */);
```

Thanks again.

**Comment by Sampozzo** [comment]
Hello? Is this project dead? Two issue in 15 days and no reply at all.

**Comment by DansDesigns** [comment]
this works:

// ILI9488:
Arduino_DataBus *bus = new Arduino_ESP32SPI(1 /* DC */, 5 /* CS */, 2 /* SCK */, 4 /* MOSI */, -1 /* MISO */, 60000000);
Arduino_ILI9488_18bit *gfx = new Arduino_ILI9488_18bit(bus, 6 /* RST */, 1 /* rotation */);

with option 1:

  // #####################################
    /* Option 1:
       crop 256 x 240 to 240 x 214
       then scale up width x 2 and scale up height x 1.5
       repeat a line for every 2 lines */
    // #####################################

    gfx->writeAddrWindow(frame_x, frame_y, frame_width, frame_height);
        for (int16_t i = 10; i < (10 + 214); i++)
        {
          gfx->writeIndexedPixelsDouble((uint8_t *)(data[i] + 8), myPalette, frame_line_pixels);
          if ((i % 2) == 1)
          {
            gfx->writeIndexedPixelsDouble((uint8_t *)(data[i] + 8), myPalette, frame_line_pixels);
          }
        }
