### ISSUE TITLE
ESP32 and ESP32-S3 errors /bitmap.c -- block corrupt

### ISSUE THREAD

**Issue by dejavu1987** [moononournation/arduino-nofrendo#9]
I have tried few different pin config for display and controller, the farthes I could get was, the splash screen appears with Nofriendo logo and then the error is logged on the console

`addr: 0x3FCBBA10, size: 61440, line 86 of /Users/.../Documents/Arduino/libraries/arduino-nofrendo/src/bitmap.c -- block corrupt`

Could you please help me understand the issue? Is it because I am using WROOM module? does this only work with WROVER?

**Comment by scanlight** [comment]
um using wrover, same issue

**Comment by and3rson** [comment]
I'm having the same issue with ESP32C3 SuperMini.

**Comment by and3rson** [comment]
Seems like something is interrupting the frame rendering. My display works fine (I can draw a diagonal line before starting main nofrendo loop).
However, with the following code in my `display_write_frame(const uint8_t *data[])`:

```cpp
    gfx->startWrite();
    if (w < 480)
    {
        gfx->writeAddrWindow(frame_x, frame_y, frame_width, frame_height);
        nofrendo_log_printf("Start\n");
        for (int32_t i = 0; i < NES_SCREEN_HEIGHT; i++)
        {
            writeIndexedPixels((uint8_t *)(data[i] + frame_x_offset), myPalette, frame_line_pixels);
        }
        nofrendo_log_printf("End\n");
    }
    gfx->endWrite();
```

...I get this output:

> Start
> _my_malloc: 6449 at .pio/libdeps/esp32c3/arduino-nofrendo/src/libsnss/libsnss.c:418
> GUI: State 0 saved
> GUI: State 0 restored

(after few more seconds)

> addr: 0x3FCBE74C, size: 61440, line 86 of .pio/libdeps/esp32c3/arduino-nofrendo/src/bitmap.c -- block corrupt

"End" is never printed. Sometimes it is, sometimes not. The screen remains containing the diagonal line I drew before starting main nofrendo loop.

However, if I add `nofrendo_log_printf("line %d of %d: \n", i, NES_SCREEN_HEIGHT);` before calling `writeIndexedPixels`, I can sometimes see all prints (including "End"). But sometimes only some "line X of X" are printed:

> Start
> line 0 of 240:
> line 1 of 240:
> line 2 of 240:
> line 3 of 240:
> _my_malloc: 6449 at .pio/libdeps/esp32c3/arduino-nofrendo/src/libsnss/libsnss.c:418
> line 4 of 240:
> line 5 of 240:
> line 6 of 240:
> line 7 of 240:
> line 8 of 240:
> line 9 of 240:
> line 10 of 240:
> line 11 of 240:
> line 12 of 240:
> line 13 of 240:
> line 14 of 240:
> line 15 of 240:
> line 16 of 240:
> line 17 of 240:
> GUI: State 0 saved
> GUI: State 0 restored
> addr: 0x3FCBED44, size: 61440, line 86 of .pio/libdeps/esp32c3/arduino-nofrendo/src/bitmap.c -- block corrupt
> addr: 0x3FCBED44, size: 61440, line 86 of .pio/libdeps/esp32c3/arduino-nofrendo/src/bitmap.c -- block corrupt


Also the screen still remains blank. Seems like there's some race condition happening somewhere... But where?

**Comment by and3rson** [comment]
Update: seems like nothing is being drawn at all. Here's my code:

```cpp
extern void display_begin() {
    gfx->begin();
    bg_color = gfx->color565(24, 24, 64); // DARK BLUE
    gfx->fillScreen(bg_color); // Works
    gfx->drawLine(0, 0, 64, 64, gfx->color565(255, 0, 0)); // Works
}

// ...

extern "C" void display_write_frame(const uint8_t *data[]) {
    nofrendo_log_printf("Drawing pixel\n");
    gfx->drawPixel(120, 140, gfx->color565(255, 255, 255)); // Does not work
}
```

I can see the red line (from `display_begin`), but not the white pixel from `display_write_frame`. The latter is definitely being called (I can see the print).

I'm using ESP32-C3 with SPIFFS. The ROM is read properly. Can it be that SPIFFS somehow messes up display's SPI?
My display is initialized as follows:

```cpp
Arduino_DataBus *bus = new Arduino_ESP32SPI(3 /* DC */, 21 /* CS */, 0, 1, -1);
Arduino_ST7789 *gfx = new Arduino_ST7789(bus, 2 /* RST */, 0 /* rotation */, true /* IPS */);
```

I can see that DataBus correctly handles ESP32-C3 (`#ifdef CONFIG_IDF_TARGET_ESP32C3`   section).

**Comment by and3rson** [comment]
I found a workaround.

It seems like something is either corrupting SPI display pin states (I'm using 1.68" 240x280 ST7789 display), or somehow corrupting my instance of Adafruit_ST7789 itself.
I did a quick test and modified my code to run `display_begin` and `display_init` INSIDE `display_write_frame` as such:

```cpp
extern "C" void display_write_frame(const uint8_t *data[]) {
    if (!inited) {
        nofrendo_log_printf("init display\n");
        display_begin();
        display_init();
        inited = true;
        nofrendo_log_printf("init display done\n");
    }
    // Rest of code form example implementation omitted for brevity.
}
```

Now everything works as expected. I'll try probing my SPI bus with a logic analyzer to see if it actually goes haywire at some place before frame rendering starts. I also checked the rest of example code and removed any pinMode/etc stuff that might have damaged the SPI bus, but still no luck finding the root cause.

Also, for some reason `displayTask` is only getting called once, and I have no idea why. So as another workaround, I'm simply calling it directly from `custom_blit`...

**Comment by and3rson** [comment]
Nevermind - it's my own dumb self... I defined same pins for some of the inputs.
However the issue with displayTask not getting called still persists.

**Comment by and3rson** [comment]
I was able to make the example working by increasing displayTask priority. This finally made it run more than once.

```cpp
xTaskCreatePinnedToCore(displayTask, "displayTask", 2048, NULL, 10, NULL, 0);
```

This seems to be more friendly with respect to the simulation, but the movement feels jerky (since the display is not catching up with the game logic).
So I've decided to stick with calling `display_write_frame` from within `custom_blit`. This obviously slows down the game a little bit, but it feels way more smooth.

**Comment by minghaojiang** [comment]
Same issue with me on ESP32 Wrover.  And seems the work around does not work on mine.

**Comment by roundspring2003** [comment]
Same issue with me on ESP32 Wrover. And seems the work around does not work on mine.

**Comment by minghaojiang** [comment]
It probably relates hardware.  It was solved by changing a ESP32.  Not sure the rootcause.  But it works on one of my ESP32 Wrover and ESP32 S2.  Although ESP32 S2 is not powerful enough and fps is low.

**Comment by minghaojiang** [comment]
Should be not a issue.  The worked EPS32 also raises this error, but it works.
